Verbunden mit Python 3.10.5

In [1]:
# Step 1: Import packages, functions, and classes
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

# Step 2: Get data
x = np.arange(10).reshape(-1, 1)
y = np.array([0, 1, 0, 0, 1, 1, 1, 1, 1, 1])

# Step 3: Create a model and train it
model = LogisticRegression(solver='liblinear', C=10.0, random_state=0)
model.fit(x, y)

# Step 4: Evaluate the model
p_pred = model.predict_proba(x)
y_pred = model.predict(x)
score_ = model.score(x, y)
conf_m = confusion_matrix(y, y_pred)
report = classification_report(y, y_pred)

In [2]:
print(report)

              precision    recall  f1-score   support

           0       0.67      0.67      0.67         3
           1       0.86      0.86      0.86         7

    accuracy                           0.80        10
   macro avg       0.76      0.76      0.76        10
weighted avg       0.80      0.80      0.80        10



In [3]:
x

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [4]:
# Step 1: Import packages, functions, and classes
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

# Step 2: Get data
x = np.arange(10).reshape(-1, 1)
y = np.array([0, 1, 0, 0, 1, 1, 1, 1, 1, 1])

# Step 3: Create a model and train it
model = LogisticRegression()
model.fit(x, y)

# Step 4: Evaluate the model
p_pred = model.predict_proba(x)
y_pred = model.predict(x)
score_ = model.score(x, y)
conf_m = confusion_matrix(y, y_pred)
report = classification_report(y, y_pred)

In [5]:
print(report)

              precision    recall  f1-score   support

           0       0.67      0.67      0.67         3
           1       0.86      0.86      0.86         7

    accuracy                           0.80        10
   macro avg       0.76      0.76      0.76        10
weighted avg       0.80      0.80      0.80        10



In [6]:
# Step 1: Import packages, functions, and classes
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

# Step 2: Get data
X = 2.5 * np.random.randn(100) + 1.5   # Array of 100 values with mean = 1.5, stddev = 2.5
res = 0.5 * np.random.randn(100)       # Generate 100 residual terms
y = 2 + 0.3 * X + res                  # Actual values of Y

# Create pandas dataframe to store our X and y values
df = pd.DataFrame(
    {'X': X,
     'y': y}
)

NameError: name 'pd' is not defined

In [7]:
# Step 1: Import packages, functions, and classes
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd

# Step 2: Get data
X = 2.5 * np.random.randn(100) + 1.5   # Array of 100 values with mean = 1.5, stddev = 2.5
res = 0.5 * np.random.randn(100)       # Generate 100 residual terms
y = 2 + 0.3 * X + res                  # Actual values of Y

# Create pandas dataframe to store our X and y values
df = pd.DataFrame(
    {'X': X,
     'y': y}
)

In [8]:
# Step 1: Import packages, functions, and classes
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd

# Step 2: Get data
X = 2.5 * np.random.randn(100) + 1.5   # Array of 100 values with mean = 1.5, stddev = 2.5
X2 = 2.5 * np.random.binomial(100) + 1.5   # Array of 100 values with mean = 1.5, stddev = 2.5

res = 0.5 * np.random.randn(100)       # Generate 100 residual terms
y = 2 + 0.3 * X + res                  # Actual values of Y

# Create pandas dataframe to store our X and y values
df = pd.DataFrame(
    {'X': X,
     'y': y}
)
p <- 1/(1 + exp(-xb))
Y<-rbinom(n, size = 1, prob = p)

TypeError: binomial() takes at least 2 positional arguments (1 given)

In [9]:
# Step 1: Import packages, functions, and classes
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd

# Step 2: Get data
X = 2.5 * np.random.randn(100) + 1.5   # Array of 100 values with mean = 1.5, stddev = 2.5
X2 = 2.5 * np.random.binomial(100, 0.3)   # Array of 100 values with mean = 1.5, stddev = 2.5

res = 0.5 * np.random.randn(100)       # Generate 100 residual terms
y = 2 + 0.3 * X + 0.8 * X2 + res                  # Actual values of Y

# Create pandas dataframe to store our X and y values
df = pd.DataFrame(
    {'X': X,
     'y': y}
)
p <- 1/(1 + exp(-xb))
Y<-rbinom(n, size = 1, prob = p)

NameError: name 'p' is not defined

In [10]:
# Step 1: Import packages, functions, and classes
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd

# Step 2: Get data
X = 2.5 * np.random.randn(100) + 1.5   # Array of 100 values with mean = 1.5, stddev = 2.5
X2 = 2.5 * np.random.binomial(100, 0.3)   # Array of 100 values with mean = 1.5, stddev = 2.5

res = 0.5 * np.random.randn(100)       # Generate 100 residual terms
xb = 2 + 0.3 * X + 0.8 * X2 + res                  # Actual values of Y

p = 1/(1 + exp(-xb))

# Create pandas dataframe to store our X and y values
df = pd.DataFrame(
    {'X': X,
     'y': y}
)

Y<-rbinom(n, size = 1, prob = p)

NameError: name 'exp' is not defined

In [11]:
# Step 1: Import packages, functions, and classes
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd
import numpy as np

# Step 2: Get data
X = 2.5 * np.random.randn(100) + 1.5   # Array of 100 values with mean = 1.5, stddev = 2.5
X2 = 2.5 * np.random.binomial(100, 0.3)   # Array of 100 values with mean = 1.5, stddev = 2.5

res = 0.5 * np.random.randn(100)       # Generate 100 residual terms
xb = 2 + 0.3 * X + 0.8 * X2 + res                  # Actual values of Y

p = 1/(1 + np.exp(-xb))

# Create pandas dataframe to store our X and y values
df = pd.DataFrame(
    {'X': X,
     'y': y}
)

Y<-rbinom(n, size = 1, prob = p)

NameError: name 'Y' is not defined

In [12]:
# Step 1: Import packages, functions, and classes
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd
import numpy as np

# Step 2: Get data
X = 2.5 * np.random.randn(100) + 1.5   # Array of 100 values with mean = 1.5, stddev = 2.5
X2 = 2.5 * np.random.binomial(100, 0.3)   # Array of 100 values with mean = 1.5, stddev = 2.5

res = 0.5 * np.random.randn(100)       # Generate 100 residual terms
xb = 2 + 0.3 * X + 0.8 * X2 + res                  # Actual values of Y

p = 1/(1 + np.exp(-xb))

# Create pandas dataframe to store our X and y values
df = pd.DataFrame(
    {'X': X,
     'y': y}
)

Y<-np.random.binomial(100, size = 1, prob = p)

NameError: name 'Y' is not defined

In [13]:
# Step 1: Import packages, functions, and classes
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd
import numpy as np

# Step 2: Get data
X = 2.5 * np.random.randn(100) + 1.5   # Array of 100 values with mean = 1.5, stddev = 2.5
X2 = 2.5 * np.random.binomial(100, 0.3)   # Array of 100 values with mean = 1.5, stddev = 2.5

res = 0.5 * np.random.randn(100)       # Generate 100 residual terms
xb = 2 + 0.3 * X + 0.8 * X2 + res                  # Actual values of Y

p = 1/(1 + np.exp(-xb))

# Create pandas dataframe to store our X and y values
df = pd.DataFrame(
    {'X': X,
     'y': y}
)

Y = np.random.binomial(100, size = 1, prob = p)

TypeError: binomial() takes at least 2 positional arguments (1 given)

In [14]:
# Step 1: Import packages, functions, and classes
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd
import numpy as np

# Step 2: Get data
X = 2.5 * np.random.randn(100) + 1.5   # Array of 100 values with mean = 1.5, stddev = 2.5
X2 = 2.5 * np.random.binomial(100, 0.3)   # Array of 100 values with mean = 1.5, stddev = 2.5

res = 0.5 * np.random.randn(100)       # Generate 100 residual terms
xb = 2 + 0.3 * X + 0.8 * X2 + res                  # Actual values of Y

p = 1/(1 + np.exp(-xb))

# Create pandas dataframe to store our X and y values
df = pd.DataFrame(
    {'X': X,
     'y': y}
)

Y = np.random.binomial(100,p)

In [15]:
Y

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100])

In [16]:
p

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
np.random.binomial(100, 0.3)

26

In [18]:
np.random.binomial(100, 0.3)

28

In [19]:
np.random.binomial(1, 0.3)

0

In [20]:


np.random.binomial(1, 0.3)

0

In [21]:


np.random.binomial(1, 0.3)

0

In [22]:


np.random.binomial(1, 0.3)

1

In [23]:
# Step 1: Import packages, functions, and classes
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd
import numpy as np

# Step 2: Get data
X = 2.5 * np.random.randn(100) + 1.5   # Array of 100 values with mean = 1.5, stddev = 2.5
X2 = 2.5 * [np.random.binomial(1, 0.3) for i in range(0,100) )   # Array of 100 values with mean = 1.5, stddev = 2.5

res = 0.5 * np.random.randn(100)       # Generate 100 residual terms
xb = 2 + 0.3 * X + 0.8 * X2 + res                  # Actual values of Y

p = 1/(1 + np.exp(-xb))

# Create pandas dataframe to store our X and y values
df = pd.DataFrame(
    {'X': X,
     'y': y}
)

Y = np.random.binomial(100,p)

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (<ipython-input-23-bc3d6baf63bd>, line 11)

In [24]:
# Step 1: Import packages, functions, and classes
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd
import numpy as np

# Step 2: Get data
X = 2.5 * np.random.randn(100) + 1.5   # Array of 100 values with mean = 1.5, stddev = 2.5
X2 = 2.5 * [np.random.binomial(1, 0.3) for i in range(0,100) ]   # Array of 100 values with mean = 1.5, stddev = 2.5

res = 0.5 * np.random.randn(100)       # Generate 100 residual terms
xb = 2 + 0.3 * X + 0.8 * X2 + res                  # Actual values of Y

p = 1/(1 + np.exp(-xb))

# Create pandas dataframe to store our X and y values
df = pd.DataFrame(
    {'X': X,
     'y': y}
)

Y = np.random.binomial(100,p)

TypeError: can't multiply sequence by non-int of type 'float'

In [25]:
# Step 1: Import packages, functions, and classes
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd
import numpy as np

# Step 2: Get data
X = 2.5 * np.random.randn(100) + 1.5   # Array of 100 values with mean = 1.5, stddev = 2.5
X2 = [np.random.binomial(1, 0.3) for i in range(0,100) ]   # Array of 100 values with mean = 1.5, stddev = 2.5

res = 0.5 * np.random.randn(100)       # Generate 100 residual terms
xb = 2 + 0.3 * X + 0.8 * X2 + res                  # Actual values of Y

p = 1/(1 + np.exp(-xb))

# Create pandas dataframe to store our X and y values
df = pd.DataFrame(
    {'X': X,
     'y': y}
)

Y = np.random.binomial(100,p)

TypeError: can't multiply sequence by non-int of type 'float'

In [26]:
# Step 1: Import packages, functions, and classes
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd
import numpy as np

# Step 2: Get data
X = 2.5 * np.random.randn(100) + 1.5   # Array of 100 values with mean = 1.5, stddev = 2.5
X2 = [np.random.binomial(1, 0.3) for i in range(0,100) ]   # Array of 100 values with mean = 1.5, stddev = 2.5

In [27]:
X2

[1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0]

In [28]:
X

array([ 0.64741895,  0.23448428,  1.7696243 ,  0.31773242,  0.43295809,
       -0.19696328,  3.72054351,  1.46544856,  7.37569927,  0.41074644,
        1.88094495, -1.81514182,  3.72086438,  3.59526045, -0.50121215,
       -0.98514572,  2.18185598,  3.32331484, -2.49268657,  6.79335938,
        3.51967863,  0.50411237,  2.05007278,  1.53224834,  1.39621231,
        1.39209434,  1.33781062, -1.76620837,  2.6609946 , -0.55351489,
       -1.07464715,  1.67079056, -0.98515804,  0.649638  ,  1.77528903,
       -1.2219257 ,  3.38967557, -0.67420264, -1.86823159, -1.16906276,
       -0.30685956,  3.00094865,  6.12537609,  2.59363001,  2.98196225,
        0.52254089, -0.10076177, -1.45461494,  2.57713055, -0.68820683,
        0.30828187,  3.61928806,  3.49280543,  4.77843463,  3.35932015,
       -2.43321503,  5.45600415,  4.13153937,  0.04252688,  2.86050071,
        3.08676071,  0.43290345,  0.72558903, -2.13106369,  3.185269  ,
        5.46003217, -0.19574386, -0.63161839,  0.90220973, -2.78

In [29]:
res = 0.5 * np.random.randn(100)       # Generate 100 residual terms
xb = 2 + 0.3 * X + 0.8 * X2 + res                  # Actual values of Y

TypeError: can't multiply sequence by non-int of type 'float'

In [30]:
res = 0.5 * np.random.randn(100)       # Generate 100 residual terms
xb = 2 + 0.3 * X + 0.8 * float(X2) + res                  # Actual values of 

TypeError: float() argument must be a string or a real number, not 'list'

In [31]:
res = 0.5 * np.random.randn(100)       # Generate 100 residual terms
xb = 2 + 0.3 * X + 0.8 * list(X2) + res                  # Actual values of Y

TypeError: can't multiply sequence by non-int of type 'float'

In [32]:
X

array([ 0.64741895,  0.23448428,  1.7696243 ,  0.31773242,  0.43295809,
       -0.19696328,  3.72054351,  1.46544856,  7.37569927,  0.41074644,
        1.88094495, -1.81514182,  3.72086438,  3.59526045, -0.50121215,
       -0.98514572,  2.18185598,  3.32331484, -2.49268657,  6.79335938,
        3.51967863,  0.50411237,  2.05007278,  1.53224834,  1.39621231,
        1.39209434,  1.33781062, -1.76620837,  2.6609946 , -0.55351489,
       -1.07464715,  1.67079056, -0.98515804,  0.649638  ,  1.77528903,
       -1.2219257 ,  3.38967557, -0.67420264, -1.86823159, -1.16906276,
       -0.30685956,  3.00094865,  6.12537609,  2.59363001,  2.98196225,
        0.52254089, -0.10076177, -1.45461494,  2.57713055, -0.68820683,
        0.30828187,  3.61928806,  3.49280543,  4.77843463,  3.35932015,
       -2.43321503,  5.45600415,  4.13153937,  0.04252688,  2.86050071,
        3.08676071,  0.43290345,  0.72558903, -2.13106369,  3.185269  ,
        5.46003217, -0.19574386, -0.63161839,  0.90220973, -2.78

In [33]:
res = 0.5 * np.random.randn(100)       # Generate 100 residual terms
xb = 2 + 0.3 * X + 0.8 * np.array(X2) + res                  # Actual values of 

In [34]:
xb

array([4.45016091, 3.12287865, 2.93747664, 2.07903644, 2.18785889,
       2.28095585, 2.41792913, 2.80087119, 4.24314177, 2.1731128 ,
       3.06063915, 2.51517093, 3.23679067, 3.16140769, 1.76886227,
       1.53877389, 1.90932377, 3.13170652, 1.23393291, 2.48337411,
       2.91389352, 2.58835304, 3.90529494, 2.86024384, 2.96994986,
       2.56101571, 3.72069325, 1.04474752, 2.75665681, 2.08750449,
       2.78095705, 2.33711954, 2.37525749, 1.91872263, 3.37384217,
       1.36750424, 2.41191925, 1.9982993 , 0.57185522, 2.75616507,
       1.69420511, 3.10279671, 3.86424752, 2.54424857, 2.23924332,
       2.22838453, 2.31540833, 0.31991768, 2.7288044 , 1.87968411,
       2.38128753, 2.68576809, 2.61711676, 4.20506958, 3.67128002,
       0.92636186, 3.60917357, 4.12103899, 2.0098067 , 2.34810308,
       3.79076888, 2.49059128, 2.93158547, 1.74680788, 3.34793246,
       4.29969494, 2.77485608, 3.01514619, 2.3373192 , 1.40058944,
       2.22965633, 2.44177459, 1.50219356, 4.28551732, 1.78252

In [35]:
p = 1/(1 + np.exp(-xb))

# Create pandas dataframe to store our X and y values
df = pd.DataFrame(
    {'X': X,
     'y': y}
)

Y = np.random.binomial(100,p)

In [36]:
Y

array([ 98,  93,  96,  90,  89,  96,  91,  95,  97,  90,  93,  94,  94,
        94,  79,  81,  86,  95,  73,  94,  94,  97,  97,  96,  94,  91,
        97,  74,  95,  93,  91,  86,  93,  89,  95,  84,  87,  86,  70,
        94,  83,  98,  99,  94,  91,  95,  91,  62,  95,  85,  93,  92,
        93, 100,  97,  69, 100,  99,  85,  92,  99,  96,  98,  86,  98,
       100,  93,  93,  89,  80,  89,  91,  74,  99,  89,  98,  95,  84,
        99,  94,  92,  78,  80,  80,  94, 100,  97,  96,  92,  96,  97,
        98,  98,  96,  79,  79,  97,  93,  98,  97])

In [37]:
p = 1/(1 + np.exp(-xb))

# Create pandas dataframe to store our X and y values
df = pd.DataFrame(
    {'X': X,
     'y': y}
)

Y = [ np.random.binomial(1,p) for p in p]

In [38]:
Y

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1]

Kein Kernel verbunden